import Link from 'next/link'
import {
  Sparkles,
  CalendarClock,
  Mail,
  CheckCircle2,
  ArrowRight,
  Copy,
  ShieldCheck,
  Users,
  Palette,
  Send,
  ScrollText,
  Camera,
  ThumbsUp,
  MapPin,
  Coffee,
  Scissors,
  Dumbbell,
  Wrench,
  ShoppingBag,
  Stethoscope,
  Building2,
  PawPrint,
} from 'lucide-react'
import SiteNav from '@/components/SiteNav'
import AgentHeroCard from '@/components/AgentHeroCard'
import CountUp from '@/components/CountUp'
import Reveal from '@/components/Reveal'

const stats = [
  { to: 156, suffix: '', label: 'social posts written a year' },
  { to: 52, suffix: '', label: 'newsletters sent automatically' },
  { to: 78, suffix: ' hrs', label: 'of marketing work saved' },
  { to: 100, suffix: '%', label: 'run by the AI agent' },
]

const industries = [
  { icon: Coffee, label: 'Cafés & Restaurants' },
  { icon: Scissors, label: 'Salons & Spas' },
  { icon: Dumbbell, label: 'Gyms & Fitness' },
  { icon: Wrench, label: 'Contractors & Trades' },
  { icon: ShoppingBag, label: 'Retail & Boutiques' },
  { icon: Stethoscope, label: 'Dental & Health' },
  { icon: Building2, label: 'Real Estate' },
  { icon: PawPrint, label: 'Pet Services' },
]

const steps = [
  {
    icon: <Sparkles className="w-5 h-5 text-brand-teal" />,
    step: '01',
    title: 'Tell Bloom about your business',
    desc: 'Your business type, your voice, and what you want to promote this week. Under 5 minutes, no credit card.',
  },
  {
    icon: <CalendarClock className="w-5 h-5 text-brand-teal" />,
    step: '02',
    title: 'The agent writes your week',
    desc: 'Three social posts and a full email newsletter, in your brand voice, generated by Gemini in about 15 seconds.',
  },
  {
    icon: <Send className="w-5 h-5 text-brand-teal" />,
    step: '03',
    title: 'It runs itself every Monday',
    desc: 'Your newsletter is emailed to your subscribers automatically. Your social captions are ready to paste. Every action is logged.',
  },
]

const faqs = [
  {
    q: 'Does Bloom post to my social accounts automatically?',
    a: 'Your email newsletter is sent to your subscribers automatically every Monday. Social captions for Instagram, Facebook, and Google are written and formatted for you to copy and paste in seconds. Bloom does not publish to third-party social accounts on your behalf.',
  },
  {
    q: 'Can I review or edit anything before it goes out?',
    a: 'Yes. You see a full preview of everything the agent writes, and you can update your promotions and voice anytime from your dashboard.',
  },
  {
    q: 'How does Bloom learn my brand voice?',
    a: 'You pick a voice during setup (friendly, professional, bold, and more), and every piece of content is generated to match it.',
  },
  {
    q: 'What does the AI actually do on its own?',
    a: 'A scheduled agent runs every week with no human trigger. It generates that week of content with Google Gemini, emails your newsletter through Resend, and records every action to your activity log.',
  },
  {
    q: 'Is there a contract?',
    a: 'No. Pro is month to month and you can cancel in one click anytime.',
  },
  {
    q: 'Where does my subscriber list live?',
    a: 'In your Bloom dashboard. You get a public subscribe page to share with customers so your list keeps growing.',
  },
]

export default function HomePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <SiteNav />

      <main className="flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden">
          <div className="aurora" />
          <div className="relative z-10 max-w-6xl mx-auto px-6 pt-16 pb-20 lg:pt-24 lg:pb-28 grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="glass inline-flex items-center gap-2 text-foreground text-sm font-medium px-3.5 py-1.5 rounded-full mb-6">
                <Sparkles className="w-4 h-4 text-brand-teal" />
                AI marketing agent for local businesses
              </div>
              <h1 className="font-display text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-[1.05] tracking-tight text-foreground">
                Your local business, on marketing{' '}
                <span className="font-serif italic font-normal text-brand-teal">autopilot.</span>
              </h1>
              <p className="text-lg text-muted max-w-xl mt-6 leading-relaxed">
                Bloom writes your weekly newsletter and social posts, emails the newsletter to your subscribers
                automatically, and hands you ready-to-paste captions. Set it up once.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 mt-8">
                <Link href="/setup" className="btn-primary text-base py-3 px-7">
                  Preview my AI content free
                  <ArrowRight className="w-4 h-4" />
                </Link>
                <a href="#how-it-works" className="btn-outline text-base py-3 px-7">
                  See how it works
                </a>
              </div>
              <p className="text-sm text-muted mt-4">
                No card to preview. Your free sample is ready in about 15 seconds.
              </p>
            </div>

            <Reveal delay={80}>
              <AgentHeroCard />
            </Reveal>
          </div>
        </section>

        {/* Stat strip */}
        <section className="bg-ink-dark text-white py-10 px-6">
          <div className="max-w-6xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {stats.map((s) => (
              <div key={s.label}>
                <div className="font-mono text-3xl sm:text-4xl font-bold text-white">
                  <CountUp to={s.to} suffix={s.suffix} />
                </div>
                <div className="text-sm text-white/60 mt-1">{s.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Industry marquee */}
        <section className="py-12 bg-surface border-y border-border overflow-hidden">
          <p className="text-center text-sm font-medium text-muted mb-6">Built for every kind of local business</p>
          <div className="marquee-wrap marquee-mask">
            <div className="marquee gap-3">
              {[...industries, ...industries].map((it, i) => (
                <span
                  key={i}
                  className="shrink-0 inline-flex items-center gap-2 bg-card border border-border rounded-full px-4 py-2 text-sm text-foreground font-medium"
                >
                  <it.icon className="w-4 h-4 text-brand-teal" />
                  {it.label}
                </span>
              ))}
            </div>
          </div>
        </section>

        {/* How it works */}
        <section id="how-it-works" className="max-w-6xl mx-auto px-6 py-24">
          <Reveal>
            <h2 className="text-3xl sm:text-4xl font-bold text-center text-foreground">How Bloom works</h2>
            <p className="text-center text-muted mt-3 mb-14 max-w-xl mx-auto">
              Three steps, then the agent takes over.
            </p>
          </Reveal>
          <div className="grid sm:grid-cols-3 gap-6">
            {steps.map((s, i) => (
              <Reveal key={s.step} delay={i * 80}>
                <div className="card card-hover h-full flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <div className="w-10 h-10 bg-brand-teal/10 rounded-xl flex items-center justify-center">{s.icon}</div>
                    <span className="font-mono text-sm text-muted">{s.step}</span>
                  </div>
                  <h3 className="font-semibold text-foreground text-lg">{s.title}</h3>
                  <p className="text-muted text-sm leading-relaxed">{s.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </section>

        {/* Agent command center (dark proof) */}
        <section id="proof" className="relative overflow-hidden bg-ink-dark text-white py-24 px-6">
          <div className="aurora opacity-25" />
          <div className="relative z-10 max-w-6xl mx-auto">
            <Reveal>
              <div className="max-w-2xl">
                <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 text-white/80 text-sm font-medium px-3.5 py-1.5 rounded-full mb-5">
                  <span className="relative flex h-2 w-2">
                    <span className="absolute inline-flex h-full w-full rounded-full bg-brand-emerald opacity-60 animate-ping" />
                    <span className="relative inline-flex h-2 w-2 rounded-full bg-brand-emerald" />
                  </span>
                  Live agent operations
                </div>
                <h2 className="text-3xl sm:text-4xl font-bold text-white">AI that runs your marketing, not just suggests it.</h2>
                <p className="text-white/60 mt-4 leading-relaxed">
                  A scheduled agent fires every Monday with no human in the loop. It writes the week, sends the newsletter,
                  and records every step. This is a typical run.
                </p>
                <Link
                  href="/agent"
                  className="inline-flex items-center gap-1.5 text-brand-emerald hover:text-white transition-colors mt-4 text-sm font-medium"
                >
                  View the live agent feed <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </Reveal>

            <div className="grid lg:grid-cols-3 gap-4 mt-10">
              <Reveal className="lg:col-span-2">
                <div className="rounded-2xl border border-white/10 bg-white/5 backdrop-blur p-5 font-mono text-[13px] leading-relaxed">
                  <div className="flex items-center gap-2 text-white/40 mb-4 text-xs">
                    <span className="w-2.5 h-2.5 rounded-full bg-white/20" />
                    <span className="w-2.5 h-2.5 rounded-full bg-white/20" />
                    <span className="w-2.5 h-2.5 rounded-full bg-white/20" />
                    <span className="ml-2">bloom agent · weekly run</span>
                  </div>
                  {[
                    ['09:00:01', 'generate', '3 posts + 1 newsletter written', 'gemini-2.5-flash · 1.2s'],
                    ['09:00:04', 'send', 'newsletter emailed to your subscribers', 'resend'],
                    ['09:00:04', 'log', 'weekly run recorded to activity log', ''],
                  ].map(([time, action, msg, meta], i) => (
                    <div key={i} className="flex flex-wrap items-baseline gap-x-3 gap-y-1 py-1.5 border-t border-white/5 first:border-0">
                      <span className="text-brand-emerald">{time}</span>
                      <span className="text-brand-cyan w-20">{action}</span>
                      <span className="text-white/80 flex-1 min-w-[12rem]">{msg}</span>
                      {meta && <span className="text-white/40 text-xs">{meta}</span>}
                    </div>
                  ))}
                </div>
              </Reveal>

              <Reveal delay={100}>
                <div className="rounded-2xl border border-white/10 bg-white/5 backdrop-blur p-6 h-full flex flex-col gap-4">
                  <div className="text-white/60 text-sm font-medium">Every week, on its own</div>
                  {[
                    { icon: <Sparkles className="w-4 h-4" />, label: 'Generate the week of content' },
                    { icon: <Mail className="w-4 h-4" />, label: 'Email the newsletter' },
                    { icon: <ScrollText className="w-4 h-4" />, label: 'Log every action' },
                  ].map((row) => (
                    <div key={row.label} className="flex items-center gap-3 text-white">
                      <span className="w-8 h-8 rounded-lg bg-brand-emerald/15 text-brand-emerald flex items-center justify-center">
                        {row.icon}
                      </span>
                      <span className="text-sm">{row.label}</span>
                    </div>
                  ))}
                  <div className="mt-auto pt-4 border-t border-white/10 text-xs text-white/50 font-mono">
                    next run · Monday 9:00am
                  </div>
                </div>
              </Reveal>
            </div>
          </div>
        </section>

        {/* Capabilities: two honest buckets */}
        <section className="max-w-6xl mx-auto px-6 py-24">
          <Reveal>
            <h2 className="text-3xl sm:text-4xl font-bold text-center text-foreground">What Bloom handles for you</h2>
            <p className="text-center text-muted mt-3 mb-14 max-w-xl mx-auto">
              One thing is fully automated. The rest is written and ready to paste.
            </p>
          </Reveal>

          <div className="grid md:grid-cols-2 gap-6">
            <Reveal>
              <div className="card card-hover h-full bg-gradient-to-br from-brand-emerald/[0.06] to-brand-teal/[0.04] border-brand-teal/30">
                <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-emerald bg-brand-emerald/10 px-2.5 py-1 rounded-full mb-4">
                  <Send className="w-3.5 h-3.5" /> Auto-sent for you
                </div>
                <h3 className="font-semibold text-foreground text-xl">Your Monday email newsletter</h3>
                <p className="text-muted text-sm mt-2 leading-relaxed">
                  Written and emailed to your subscriber list automatically every week. You do nothing. Bloom grows the
                  list for you with a public subscribe page.
                </p>
                <ul className="mt-5 space-y-2 text-sm text-foreground/80">
                  {['Sent automatically every Monday', 'Full subscriber dashboard', 'Public subscribe page to grow your list'].map(
                    (f) => (
                      <li key={f} className="flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4 text-brand-emerald shrink-0" /> {f}
                      </li>
                    )
                  )}
                </ul>
              </div>
            </Reveal>

            <Reveal delay={80}>
              <div className="card card-hover h-full">
                <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-accent-coral bg-accent-coral/10 px-2.5 py-1 rounded-full mb-4">
                  <Copy className="w-3.5 h-3.5" /> Ready to paste in seconds
                </div>
                <h3 className="font-semibold text-foreground text-xl">Your social captions</h3>
                <p className="text-muted text-sm mt-2 leading-relaxed">
                  Three posts a week, written in your voice and formatted for each platform. Copy, paste, done.
                </p>
                <div className="mt-5 grid grid-cols-3 gap-3">
                  {[
                    { icon: <Camera className="w-4 h-4" />, label: 'Instagram' },
                    { icon: <ThumbsUp className="w-4 h-4" />, label: 'Facebook' },
                    { icon: <MapPin className="w-4 h-4" />, label: 'Google' },
                  ].map((p) => (
                    <div key={p.label} className="rounded-xl border border-border p-3 text-center">
                      <div className="w-8 h-8 mx-auto rounded-lg bg-surface flex items-center justify-center text-foreground">
                        {p.icon}
                      </div>
                      <div className="text-xs text-muted mt-2">{p.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            </Reveal>
          </div>

          <div className="grid sm:grid-cols-4 gap-4 mt-6">
            {[
              { icon: <Palette className="w-5 h-5" />, label: 'Matches your brand voice' },
              { icon: <ScrollText className="w-5 h-5" />, label: 'Full activity log of every AI action' },
              { icon: <Users className="w-5 h-5" />, label: 'Subscriber management' },
              { icon: <CalendarClock className="w-5 h-5" />, label: 'Update promotions anytime' },
            ].map((f, i) => (
              <Reveal key={f.label} delay={i * 60}>
                <div className="card card-hover h-full flex items-center gap-3 py-4">
                  <span className="w-9 h-9 rounded-lg bg-brand-teal/10 text-brand-teal flex items-center justify-center shrink-0">
                    {f.icon}
                  </span>
                  <span className="text-sm text-foreground">{f.label}</span>
                </div>
              </Reveal>
            ))}
          </div>
        </section>

        {/* Pricing */}
        <section id="pricing" className="bg-surface border-y border-border py-24 px-6">
          <div className="max-w-5xl mx-auto text-center">
            <Reveal>
              <h2 className="text-3xl sm:text-4xl font-bold text-foreground">Simple pricing</h2>
              <p className="text-muted mt-3 mb-4">One plan. Everything included. Cancel anytime.</p>
              <p className="text-sm text-muted mb-12 max-w-lg mx-auto">
                $99 a month is less than one slow-night table, or about two hours with a freelance marketer, for a full
                month of content.
              </p>
            </Reveal>
            <div className="flex flex-col md:flex-row gap-6 justify-center max-w-3xl mx-auto text-left">
              <Reveal className="flex-1">
                <div className="card h-full">
                  <div className="text-sm font-semibold text-muted uppercase tracking-wide mb-2">Preview</div>
                  <div className="text-4xl font-bold text-foreground mb-1">Free</div>
                  <p className="text-sm text-muted mb-6">See your AI-generated content before you commit.</p>
                  <ul className="space-y-2.5 text-sm text-foreground/80 mb-6">
                    {['A real week of content for your business', '3 social posts + a newsletter draft', 'No credit card required'].map(
                      (f) => (
                        <li key={f} className="flex items-center gap-2">
                          <CheckCircle2 className="w-4 h-4 text-brand-emerald" /> {f}
                        </li>
                      )
                    )}
                  </ul>
                  <Link href="/setup" className="btn-outline w-full text-sm">
                    Preview for free
                  </Link>
                </div>
              </Reveal>

              <Reveal delay={80} className="flex-1">
                <div className="card h-full relative ring-2 ring-brand-emerald">
                  <div className="absolute -top-3 left-6 bg-brand-emerald text-white text-xs font-semibold px-3 py-1 rounded-full">
                    Full autopilot
                  </div>
                  <div className="text-sm font-semibold text-brand-emerald uppercase tracking-wide mb-2">Pro</div>
                  <div className="text-4xl font-bold text-foreground mb-1">
                    $99 <span className="text-lg font-normal text-muted">/month</span>
                  </div>
                  <p className="text-sm text-muted mb-6">The full weekly agent, running on its own.</p>
                  <ul className="space-y-2.5 text-sm text-foreground/80 mb-6">
                    {[
                      '3 social posts written every week',
                      'Newsletter emailed automatically every Monday',
                      'Full agent activity dashboard',
                      'Subscriber management + subscribe page',
                      'Update promotions anytime',
                      'Cancel anytime',
                    ].map((f) => (
                      <li key={f} className="flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4 text-brand-emerald" /> {f}
                      </li>
                    ))}
                  </ul>
                  <Link href="/setup" className="btn-primary w-full text-sm">
                    Start with a free preview
                    <ArrowRight className="w-4 h-4" />
                  </Link>
                  <p className="flex items-center justify-center gap-1.5 text-xs text-muted mt-3">
                    <ShieldCheck className="w-3.5 h-3.5 text-brand-emerald" /> Love your first week or your money back
                  </p>
                </div>
              </Reveal>
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="max-w-3xl mx-auto px-6 py-24">
          <Reveal>
            <h2 className="text-3xl sm:text-4xl font-bold text-center text-foreground mb-12">Questions, answered honestly</h2>
          </Reveal>
          <div className="space-y-3">
            {faqs.map((f, i) => (
              <Reveal key={f.q} delay={i * 40}>
                <details className="group card card-hover [&_summary]:cursor-pointer">
                  <summary className="flex items-center justify-between gap-4 font-medium text-foreground list-none">
                    {f.q}
                    <ArrowRight className="w-4 h-4 text-muted shrink-0 transition-transform group-open:rotate-90" />
                  </summary>
                  <p className="text-sm text-muted leading-relaxed mt-3">{f.a}</p>
                </details>
              </Reveal>
            ))}
          </div>
        </section>

        {/* Closing CTA */}
        <section className="relative overflow-hidden px-6 py-24">
          <div className="aurora" />
          <div className="relative z-10 max-w-2xl mx-auto text-center">
            <h2 className="text-3xl sm:text-4xl font-bold text-foreground">
              See a week of your marketing, written in 15 seconds.
            </h2>
            <p className="text-muted mt-4 mb-8">No account, no credit card. Just your business info.</p>
            <Link href="/setup" className="btn-primary text-base py-3 px-10">
              Preview my content free
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t border-border bg-surface py-10 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-muted">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-brand-teal" />
            <span className="font-display font-semibold text-foreground">Bloom</span>
            <span className="text-muted">· AI marketing for local businesses</span>
          </div>
          <div className="flex items-center gap-6">
            <Link href="/setup" className="hover:text-foreground transition-colors">
              Get started
            </Link>
            <span className="text-muted">Built with Google Gemini</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
