'use client'

import { useState, useEffect, use } from 'react'
import Link from 'next/link'
import { Sparkles, Copy, Check, ArrowRight, Loader2, Mail, ExternalLink } from 'lucide-react'

type Content = {
  post1: string
  post2: string
  post3: string
  newsletterSubject: string
  newsletterHtml: string
}

export default function PreviewPage({ params }: { params: Promise<{ businessId: string }> }) {
  const { businessId } = use(params)
  const [content, setContent] = useState<Content | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState<string | null>(null)

  useEffect(() => {
    fetch('/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ businessId }),
    })
      .then((r) => r.json())
      .then((d) => {
        if (d.content) setContent(d.content)
        else setError('Failed to generate content, please try again')
      })
      .catch(() => setError('Failed to generate content, please try again'))
      .finally(() => setLoading(false))
  }, [businessId])

  async function copy(text: string, key: string) {
    await navigator.clipboard.writeText(text)
    setCopied(key)
    setTimeout(() => setCopied(null), 2000)
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-100 bg-white px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-emerald-600 rounded-md flex items-center justify-center">
              <Sparkles className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-semibold text-gray-900">Bloom</span>
          </div>
          <Link href={`/dashboard/${businessId}`} className="text-sm text-emerald-600 hover:underline flex items-center gap-1">
            Go to dashboard <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-10">
        {loading && (
          <div className="text-center py-20">
            <Loader2 className="w-10 h-10 text-emerald-600 animate-spin mx-auto mb-4" />
            <h2 className="text-xl font-semibold text-gray-900 mb-2">Generating your content…</h2>
            <p className="text-gray-500">Bloom is writing your week&apos;s marketing. This takes about 15 seconds.</p>
          </div>
        )}

        {error && (
          <div className="text-center py-20">
            <p className="text-red-500">{error}</p>
          </div>
        )}

        {content && !loading && (
          <>
            <div className="text-center mb-10">
              <div className="inline-flex items-center gap-2 bg-emerald-50 text-emerald-700 text-sm font-medium px-4 py-2 rounded-full mb-4">
                <Sparkles className="w-4 h-4" /> AI-generated by Bloom
              </div>
              <h1 className="text-3xl font-bold text-gray-900 mb-2">Your week&apos;s content is ready</h1>
              <p className="text-gray-500">
                Here&apos;s what Bloom would publish and send for you every week, automatically.
              </p>
            </div>

            {/* Social Posts */}
            <h2 className="font-semibold text-gray-900 mb-4 text-lg">This week&apos;s social posts</h2>
            <div className="space-y-4 mb-8">
              {[
                { key: 'post1', label: 'Post 1', text: content.post1 },
                { key: 'post2', label: 'Post 2', text: content.post2 },
                { key: 'post3', label: 'Post 3', text: content.post3 },
              ].map(({ key, label, text }) => (
                <div key={key} className="card bg-white">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-semibold text-emerald-600 uppercase tracking-wide">{label}</span>
                    <button
                      onClick={() => copy(text, key)}
                      className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-700 transition-colors"
                    >
                      {copied === key ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied === key ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                  <p className="text-gray-700 text-sm leading-relaxed whitespace-pre-wrap">{text}</p>
                </div>
              ))}
            </div>

            {/* Newsletter */}
            <h2 className="font-semibold text-gray-900 mb-4 text-lg flex items-center gap-2">
              <Mail className="w-5 h-5 text-emerald-600" />
              This week&apos;s newsletter
            </h2>
            <div className="card bg-white mb-8">
              <div className="flex items-start justify-between gap-3 mb-4">
                <div>
                  <div className="text-xs font-semibold text-emerald-600 uppercase tracking-wide mb-1">Subject line</div>
                  <p className="text-gray-900 font-medium">{content.newsletterSubject}</p>
                </div>
                <button
                  onClick={() => copy(content.newsletterSubject, 'subject')}
                  className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-700 shrink-0 transition-colors"
                >
                  {copied === 'subject' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied === 'subject' ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <div className="border-t border-gray-100 pt-4">
                <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">Email preview</div>
                <div
                  className="border border-gray-100 rounded-lg overflow-hidden text-sm"
                  dangerouslySetInnerHTML={{ __html: content.newsletterHtml }}
                />
              </div>
            </div>

            {/* Upgrade CTA */}
            <div className="bg-emerald-600 rounded-xl p-8 text-center text-white">
              <h2 className="text-2xl font-bold mb-2">This is what Bloom delivers every single week</h2>
              <p className="text-emerald-100 mb-6 max-w-md mx-auto">
                Activate your subscription to get this content generated and sent automatically every Monday, without lifting a finger.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link
                  href={`/api/checkout?businessId=${businessId}`}
                  className="bg-white text-emerald-700 font-semibold py-3 px-8 rounded-lg hover:bg-emerald-50 transition-colors flex items-center justify-center gap-2"
                >
                  Activate for $99/month
                  <ArrowRight className="w-4 h-4" />
                </Link>
                <Link
                  href={`/dashboard/${businessId}`}
                  className="border border-emerald-400 text-white font-medium py-3 px-6 rounded-lg hover:bg-emerald-700 transition-colors flex items-center justify-center gap-2"
                >
                  <ExternalLink className="w-4 h-4" />
                  View dashboard first
                </Link>
              </div>
              <p className="text-emerald-200 text-sm mt-4">Cancel anytime. No lock-in.</p>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
