'use client'

import { useState, useEffect, use } from 'react'
import Link from 'next/link'
import { Sparkles, Copy, Check, ArrowRight, Loader2, Mail, ExternalLink, Radar } from 'lucide-react'
import BloomMark from '@/components/BloomMark'

type Content = {
  post1: string
  post2: string
  post3: string
  newsletterSubject: string
  newsletterHtml: string
}

export default function PreviewPage({ params }: { params: Promise<{ businessId: string }> }) {
  const { businessId } = use(params)
  const [content, setContent] = useState<Content | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState<string | null>(null)
  // Owner-only dashboard token, kept in this browser. Anyone who was merely
  // sent this preview link will not have it, so no dashboard link renders.
  const [dashToken, setDashToken] = useState<string | null>(null)

  useEffect(() => {
    try {
      setDashToken(localStorage.getItem(`bloom_dt_${businessId}`))
    } catch {
      /* storage unavailable */
    }
  }, [businessId])

  useEffect(() => {
    fetch('/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ businessId }),
    })
      .then((r) => r.json())
      .then((d) => {
        if (d.content) setContent(d.content)
        else setError('Failed to generate content, please try again')
      })
      .catch(() => setError('Failed to generate content, please try again'))
      .finally(() => setLoading(false))
  }, [businessId])

  async function copy(text: string, key: string) {
    await navigator.clipboard.writeText(text)
    setCopied(key)
    setTimeout(() => setCopied(null), 2000)
  }

  return (
    <div className="min-h-screen bg-surface">
      <header className="border-b border-border bg-card px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BloomMark className="w-6 h-6" />
            <span className="font-display font-bold text-foreground">Bloom</span>
          </div>
          {dashToken && (
            <Link
              href={`/dashboard/${businessId}?t=${dashToken}`}
              className="text-sm text-emerald-600 hover:underline flex items-center gap-1"
            >
              Go to dashboard <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          )}
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-10">
        {loading && (
          <div className="text-center py-20">
            <Loader2 className="w-10 h-10 text-emerald-600 animate-spin mx-auto mb-4" />
            <h2 className="text-xl font-semibold text-foreground mb-2">Generating your content…</h2>
            <p className="text-muted">Bloom is writing your week&apos;s marketing. This takes under a minute.</p>
          </div>
        )}

        {error && (
          <div className="text-center py-20">
            <p className="text-red-500">{error}</p>
          </div>
        )}

        {content && !loading && (
          <>
            <div className="text-center mb-10">
              <div className="inline-flex items-center gap-2 bg-brand-emerald/10 text-brand-emerald-text text-sm font-medium px-4 py-2 rounded-full mb-4">
                <Sparkles className="w-4 h-4" /> AI-generated by Bloom
              </div>
              <h1 className="text-3xl font-bold text-foreground mb-2">Your week&apos;s content is ready</h1>
              <p className="text-muted">
                Here&apos;s what Bloom would publish and send for you every week, automatically.
              </p>
            </div>

            {/* Social Posts */}
            <h2 className="font-semibold text-foreground mb-4 text-lg">This week&apos;s social posts</h2>
            <div className="space-y-4 mb-8">
              {[
                { key: 'post1', label: 'Post 1', text: content.post1 },
                { key: 'post2', label: 'Post 2', text: content.post2 },
                { key: 'post3', label: 'Post 3', text: content.post3 },
              ].map(({ key, label, text }) => (
                <div key={key} className="card bg-card">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-semibold text-brand-emerald-text uppercase tracking-wide">{label}</span>
                    <button
                      onClick={() => copy(text, key)}
                      className="flex items-center gap-1.5 text-xs text-muted hover:text-foreground transition-colors"
                    >
                      {copied === key ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied === key ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                  <p className="text-foreground text-sm leading-relaxed whitespace-pre-wrap">{text}</p>
                </div>
              ))}
            </div>

            {/* Newsletter */}
            <h2 className="font-semibold text-foreground mb-4 text-lg flex items-center gap-2">
              <Mail className="w-5 h-5 text-emerald-600" />
              This week&apos;s newsletter
            </h2>
            <div className="card bg-card mb-8">
              <div className="flex items-start justify-between gap-3 mb-4">
                <div>
                  <div className="text-xs font-semibold text-brand-emerald-text uppercase tracking-wide mb-1">Subject line</div>
                  <p className="text-foreground font-medium">{content.newsletterSubject}</p>
                </div>
                <button
                  onClick={() => copy(content.newsletterSubject, 'subject')}
                  className="flex items-center gap-1.5 text-xs text-muted hover:text-foreground shrink-0 transition-colors"
                >
                  {copied === 'subject' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied === 'subject' ? 'Copied!' : 'Copy'}
                </button>
              </div>
              <div className="border-t border-border pt-4">
                <div className="text-xs font-semibold text-muted uppercase tracking-wide mb-3">Email preview</div>
                {/* Render the newsletter inside a sandboxed iframe, NOT via
                    dangerouslySetInnerHTML. The body is model-authored HTML
                    steered by attacker-controllable business fields, so a
                    same-origin render could run script and read this owner's
                    dashboard token from localStorage. The iframe has no
                    allow-scripts, so nothing in it can touch the app origin.
                    It also frames the email on a fixed white canvas the way a
                    real inbox would, so it stays readable in dark mode. */}
                <iframe
                  title="Newsletter preview"
                  sandbox=""
                  srcDoc={`<!doctype html><html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><base target="_blank" /></head><body style="margin:0;background:#ffffff;color:#111827;font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif">${content.newsletterHtml}</body></html>`}
                  className="border border-border rounded-lg w-full bg-white"
                  style={{ height: 460 }}
                />
              </div>
            </div>

            {/* The promise on the landing page was "show me who is slipping", and
                setup delivers a content preview. Close that loop here: the radar is
                free, and it is the reason they came. */}
            {dashToken && (
              <div className="rounded-xl border border-border bg-card p-6 sm:p-8 mb-6">
                <div className="flex flex-col sm:flex-row sm:items-center gap-5">
                  <Radar className="w-6 h-6 text-brand-teal-text shrink-0" />
                  <div className="flex-1">
                    <h2 className="text-lg font-bold text-foreground">Now the part that pays for itself</h2>
                    <p className="text-sm text-muted mt-1.5 leading-relaxed">
                      Upload your booking history and I will show you which clients are slipping away from their own
                      rhythm, and what each of them is worth a year. It is free to look, and you do not need an export
                      handy to try it.
                    </p>
                  </div>
                  <Link
                    href={`/dashboard/${businessId}/clients?t=${dashToken}`}
                    className="btn-primary text-sm py-2.5 px-5 shrink-0"
                  >
                    Show me who is slipping <ArrowRight className="w-4 h-4" />
                  </Link>
                </div>
              </div>
            )}

            {/* Upgrade CTA */}
            <div className="bg-emerald-600 rounded-xl p-8 text-center text-white">
              <h2 className="text-2xl font-bold mb-2">This is your week, every Monday</h2>
              <p className="text-emerald-100 mb-6 max-w-md mx-auto">
                Starter writes your week for you to publish. Pro also emails the newsletter to your subscribers. Both
                let me write to the clients you are about to lose, which is the part that pays for itself.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link
                  href={`/api/checkout?businessId=${businessId}&plan=starter`}
                  className="border border-emerald-400 text-white font-semibold py-3 px-6 rounded-lg hover:bg-emerald-700 transition-colors flex items-center justify-center gap-2"
                >
                  Starter, $49/month
                </Link>
                <Link
                  href={`/api/checkout?businessId=${businessId}&plan=pro`}
                  className="bg-white text-emerald-700 font-semibold py-3 px-8 rounded-lg hover:bg-emerald-50 transition-colors flex items-center justify-center gap-2"
                >
                  Pro, $99/month
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
              {dashToken && (
                <Link
                  href={`/dashboard/${businessId}?t=${dashToken}`}
                  className="inline-flex items-center justify-center gap-2 text-emerald-100 hover:text-white text-sm mt-5 underline underline-offset-4"
                >
                  <ExternalLink className="w-4 h-4" />
                  View dashboard first
                </Link>
              )}
              <p className="text-emerald-200 text-sm mt-4">Cancel anytime. No lock-in.</p>
            </div>
          </>
        )}
      </div>
    </div>
  )
}
